config/routes.rb
Adventur::Application.routes.draw do
  

  resources :items
  resources :scenes
  resources :users
  resources :sessions

  get "/profile" => "profile#index", :as => "profile"

  get "/sign_up" => "users#new",     :as => "sign_up"
  
  get "/log_in"  => "sessions#new",     :as => "log_in"
  get "/log_out" => "sessions#destroy", :as => "log_out"
  
  get "/welcome" => "welcome#index", :as => "welcome"

  root :to => "welcome#index"

end

app/models/item.rb
class Item < ActiveRecord::Base

  has_attached_file :image, :styles => { :examine => "400x400>", :thumb => "100x100>" }

  validates_presence_of :name, :description
end

app/models/scene.rb
class Scene < ActiveRecord::Base
  validates_presence_of :name, :description

  has_attached_file :image, :styles => { :in_game => "400x400>", :thumb => "100x100>" }

end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :password
  
  before_save :encrypt_password
  
  validates_uniqueness_of :username
  validates_presence_of   :username
  validates_presence_of   :password, :on => :create
  validates_confirmation_of :password
  
  
  def self.authenticate(username, password)
    user = self.find_by_username(username)
    if user
      password_hash = BCrypt::Engine.hash_secret(password, user.password_salt)
      if password_hash == user.password_hash
        return user
      end
    end
    
    return nil
  end
  
  
  private
  
  def encrypt_password()
    if self.password.present?
      salt = BCrypt::Engine.generate_salt
      self.password_salt = salt
      self.password_hash = BCrypt::Engine.hash_secret(self.password, salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_user, :logged_in?
  
  private
  
  def logged_in?
    current_user != nil
  end
  
  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  
  def authorize()
    unless logged_in?
      redirect_to log_in_path, :notice => "Please log in"
      return false
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_filter :authorize

  # GET /items
  # GET /items.xml
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @items }
    end
  end

  # GET /items/1
  # GET /items/1.xml
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @item }
    end
  end

  # GET /items/new
  # GET /items/new.xml
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.xml
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to(@item, :notice => 'Item was successfully created.') }
        format.xml  { render :xml => @item, :status => :created, :location => @item }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.xml
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to(@item, :notice => 'Item was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.xml
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to(items_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController

  before_filter :authorize

  def index
  end

end

app/controllers/scenes_controller.rb
class ScenesController < ApplicationController

  before_filter :authorize

  # GET /scenes
  # GET /scenes.xml
  def index
    @scenes = Scene.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @scenes }
    end
  end

  # GET /scenes/1
  # GET /scenes/1.xml
  def show
    @scene = Scene.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @scene }
    end
  end

  # GET /scenes/new
  # GET /scenes/new.xml
  def new
    @scene = Scene.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @scene }
    end
  end

  # GET /scenes/1/edit
  def edit
    @scene = Scene.find(params[:id])
  end

  # POST /scenes
  # POST /scenes.xml
  def create
    @scene = Scene.new(params[:scene])

    respond_to do |format|
      if @scene.save
        format.html { redirect_to(@scene, :notice => 'Scene was successfully created.') }
        format.xml  { render :xml => @scene, :status => :created, :location => @scene }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @scene.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /scenes/1
  # PUT /scenes/1.xml
  def update
    @scene = Scene.find(params[:id])

    respond_to do |format|
      if @scene.update_attributes(params[:scene])
        format.html { redirect_to(@scene, :notice => 'Scene was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @scene.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /scenes/1
  # DELETE /scenes/1.xml
  def destroy
    @scene = Scene.find(params[:id])
    @scene.destroy

    respond_to do |format|
      format.html { redirect_to(scenes_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end


  def create()
    user = User.authenticate(params[:username], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to profile_url, :notice => "Logged in"
    else
      flash.now.alert = "Invalid credentials"
      render "new"
    end
  end

  def destroy()
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end



  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to log_in_url, :notice => "Account created successfully."
    else
      @user.password = ""
      @user.password_confirmation = ""
      render "new"
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/scenes_helper.rb
module ScenesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for(@item, :html => {:multipart => true}) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <div class="field" >
    <%= f.label     :notes %><br />
    <%= f.text_area :notes %>
  </div>
  
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Image</th>
    <th></th>
    <th></th>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td><%= item.name %></td>
    <td><%= item.description %></td>
    <td><%= link_to image_tag(item.image.url(:thumb)), item %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td><%= link_to 'Destroy', item, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<section id="view" >
  <%= image_tag @item.image.url(:examine) %>
</section>

<p>
  <b>Name:</b>
  <%= @item.name %>
</p>

<p>
  <%= @item.description %>
</p>

<h3>Notes</h3>

<p>
  <%= @item.notes %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Adventur</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>


<header>
  <nav id="account" >
    <% if logged_in? %>
      Hello <%= current_user.username %>.  (<%= link_to "Log out", log_out_path %>)
    <% else %>
      <%= link_to "Sign up", sign_up_path %> or <%= link_to "log in", log_in_path %>
    <% end %>
  </nav>

  <nav id="site" >
    <ul>
      <% if logged_in? %>
        <li><%= link_to "Profile", profile_path %></li>
        <li><%= link_to "Items", items_path %></li>
        <li><%= link_to "Scenes", scenes_path %></li>
      <% else %>
        <li><%= link_to "Welcome", welcome_path %></li>
      <% end %>
    </ul>
  </nav>

  
</header>

<div id="content" >
  <%= yield %>
</div>

</body>
</html>

app/views/scenes/_form.html.erb
<%= form_for(@scene, :html => {:multipart => true} ) do |f| %>
  <% if @scene.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scene.errors.count, "error") %> prohibited this scene from being saved:</h2>

      <ul>
      <% @scene.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>

  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scenes/edit.html.erb
<h1>Editing scene</h1>

<%= render 'form' %>

<%= link_to 'Show', @scene %> |
<%= link_to 'Back', scenes_path %>

app/views/scenes/index.html.erb
<h1>Listing scenes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Image</th>
    <th></th>
    <th></th>
  </tr>

<% @scenes.each do |scene| %>
  <tr>
    <td><%= scene.name %></td>
    <td><%= scene.description %></td>
    <td><%= link_to image_tag(scene.image.url(:thumb)), scene %></td>
    <td><%= link_to 'Edit', edit_scene_path(scene) %></td>
    <td><%= link_to 'Destroy', scene, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Scene', new_scene_path %>

app/views/scenes/new.html.erb
<h1>New scene</h1>

<%= render 'form' %>

<%= link_to 'Back', scenes_path %>

app/views/scenes/show.html.erb
<p id="notice"><%= notice %></p>

<section id="view" >
  <%= image_tag @scene.image.url(:in_game) %>
</section>

<h1>
  <%= @scene.name %>
</h1>

<p>
  <%= @scene.description %>
</p>

<h3>Notes</h3>

<p>
  <%= @scene.notes %>
</p>

<%= link_to 'Edit', edit_scene_path(@scene) %> |
<%= link_to 'Back', scenes_path %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  
  
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/users/new.html.erb
<h1>Create Account</h1>

<%= render "form" %>

app/views/welcome/index.html.erb
<h1>Ye Olde Welcomme Page</h1>
<p>You find yourself on the threshold of other worlds.  You see:</p>
<ul>
  <% if logged_in? %>
    <li>Your <%= link_to "profile page", profile_path %></li>
    <li>A <%= link_to "log out", log_out_path %> link</li>
  <% else %>
    <li>A <%= link_to "log in", log_in_path %> link</li>
    <li>A <%= link_to "sign up", sign_up_path %> link</li>
  <% end %>
</ul>

app/views/welcome/welcome.html.erb
<h1>Welcome#welcome</h1>
<p>Find me in app/views/welcome/welcome.html.erb</p>